### ISSUE TITLE
Skin has to be updated

### ISSUE THREAD

**Issue by madmaxgrey** [maenDisease/Steam#6]
any ETA on when the update will be avaliable or is this project dead and requires takeover

**Comment by Huderon** [comment]
![gLMgHhP](https://github.com/maenDisease/Steam/assets/92663142/f9831e0d-4098-4c82-8893-8eb3a5c7cadc)

Disease is still in basic training for another at least another 3-4 weeks.

**Comment by madmaxgrey** [comment]
ah okay thank you for letting me know
