### ISSUE TITLE
theme isn't working anymore

### ISSUE THREAD

**Issue by carrotee123** [maenDisease/Steam#9]
it just suddenly stopped working no matter how many times i reset better discord or reinstall it doesn't fix it
![image_2024-03-28_103149842](https://github.com/maenDisease/Steam/assets/84941224/4d085fab-4e60-4c45-a690-e4ffb6d7e620)

**Comment by Matiam0** [comment]
Can confirm it stopped working in particular the server list is missing.

**Comment by carrotee123** [comment]
it seems exponent the windows xp theme also doesn't work anymore was a soft update rolled out the made some custom themes break?

**Comment by 0aShadow** [comment]
Can confirm aswell, also settings menu also isnt on top of discord anymore, its back to fullscreen.
Seems like more than just this theme is broken, discord just updated something that broke half of css for nearly every theme.

**Comment by The-Grace-God** [comment]
as far as i know all of this has been fixed in vencord
![image](https://github.com/maenDisease/Steam/assets/66783188/d988362d-2a01-408d-981c-15cd50218060)
as seen here the theme is working perfectly fine

**Comment by Huderon** [comment]
Doesn't have anything to do with Vencord, The theme has just been updated since this issue was opened
